# Generated by Django 2.0.5 on 2019-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'In progress'), ('2', 'completed'), ('3', 'pending')], default='pending', max_length=30),
        ),
    ]
